server:
  port: 9000
spring:
  h2:
    console:
      enabled: true
      settings:
        trace: false
logging:
  level:
    org: info
    com: off
---
spring:
  profiles:
    active: local
---
spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data-h2.sql
      schema-locations: classpath:schema-h2.sql
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  config:
    activate:
      on-profile: local
---
spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:hr_schema_postgres.sql
      data-locations: classpath:hr_data_postgres.sql
  datasource:
    url: jdbc:postgresql://postgres.cfsimw6sk40u.eu-north-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
    show-sql: true
  config:
    activate:
      on-profile: prod
welcome:
  message: welcome
